// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpxzidmeawtdbkjeybdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweHppZG1lYXd0ZGJramV5YmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTQ2ODAsImV4cCI6MjA1NTYzMDY4MH0.Q1XvGwe8k7rj8RiBHq7NQH9SrPOpsYqsUNB4l7-Buu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);